# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_sitemap", "0001_initial"),
        ("django_sitemap", "0002_channel_skip_category_without_enabled_products"),
        ("django_sitemap", "0003_channel_contentdb_access_rights_and_more"),
        ("django_sitemap", "0004_alter_channel_category_url_and_more"),
        ("django_sitemap", "0005_channel_custom_product_url_and_more"),
        ("django_sitemap", "0006_channel_robots_txt"),
        ("django_sitemap", "0007_rename_channel_to_languagesitemap_and_create_domain_models"),
        ("django_sitemap", "0008_remove_languagesitemap_url_host_and_more"),
        ("django_sitemap", "0009_languagesitemap_faq_url"),
        ("django_sitemap", "0010_alter_domainsitemap_channel_and_more"),
    ]

    # Data ops from the old chain intentionally not carried over (no-ops on a fresh database):
    # 0007 migrated pre-existing Channel rows into the renamed LanguageSitemap + new
    # Channel/DomainSitemap models via an in-memory cache — there are no rows to migrate
    # at install time. Its DROP INDEX ... IF EXISTS cleanup is likewise unnecessary here.

    dependencies = [
        ("django_regional", "0002_reset_pk_sequences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LanguageSitemap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("channel_short_idx", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "product_url",
                    models.CharField(
                        blank=True,
                        help_text="URL prefix for product pages. Use {{language_iso2}} as a placeholder for language iso2. Also use {{channel_short_idx}} as a placeholder for channel short idx. Supports modifiers: {{language_iso2.lower()}}, {{language_iso2.upper()}}.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "category_url",
                    models.CharField(
                        blank=True,
                        help_text="URL prefix for category pages. Use {{language_iso2}} as a placeholder for language iso2. Also use {{channel_short_idx}} as a placeholder for channel short idx. Supports modifiers: {{language_iso2.lower()}}, {{language_iso2.upper()}}.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "custom_product_url",
                    models.CharField(
                        blank=True,
                        help_text="URL prefix for custom product pages. If empty, custom products will not be included in sitemap. Use {{language_iso2}} as a placeholder for language iso2. Also use {{channel_short_idx}} as a placeholder for channel short idx. Supports modifiers: {{language_iso2.lower()}}, {{language_iso2.upper()}}.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "faq_url",
                    models.CharField(
                        blank=True,
                        help_text="URL prefix for FAQ item pages. If empty, FAQ items will not be included in sitemap. Use {{language_iso2}} as a placeholder for language iso2. Also use {{channel_short_idx}} as a placeholder for channel short idx. Supports modifiers: {{language_iso2.lower()}}, {{language_iso2.upper()}}. Example: '{{language_iso2.lower()}}/faq'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contentdb_content_types_to_process",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Content types to process. Use {{language_iso2}} as a placeholder for language iso2. Also use {{channel_short_idx}} as a placeholder for channel short idx. Supports modifiers: {{language_iso2.lower()}}, {{language_iso2.upper()}}. Example: {'blog-post': '{{language_iso2.lower()}}/porady', 'static-page': '{{channel_short_idx}}/static'}",
                        null=True,
                    ),
                ),
                (
                    "contentdb_access_rights",
                    models.JSONField(
                        blank=True, default=list, help_text="Access rights contentdb. Example: [1,2]", null=True
                    ),
                ),
                (
                    "merge_languages_in_sitemap",
                    models.BooleanField(
                        default=True,
                        help_text="Jeśli zaznaczone, pliki sitemap dla różnych języków będą łączone w jeden plik dla danego kanału.",
                    ),
                ),
                (
                    "skip_category_without_enabled_products",
                    models.BooleanField(
                        default=True,
                        help_text="Jeśli zaznaczone, kategorie bez włączonych produktów nie będą generowane w sitemap.",
                    ),
                ),
                (
                    "exclude_product_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Product types to exclude from sitemap. Values: 0=ProductBase, 1=ProductSimple, 2=ProductConfigurable, 3=ProductBundle, 4=ProductCustom. Example: [2, 3] excludes Configurable and Bundle products.",
                        null=True,
                    ),
                ),
                (
                    "robots_txt",
                    models.TextField(
                        blank=True,
                        help_text="Custom robots.txt content for this channel. If empty, the default template will be used. Sitemap entries are appended automatically.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomainSitemap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=255, unique=True)),
                ("domain_url", models.CharField(max_length=2056)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_sitemaps",
                        to="django_sitemap.channel",
                    ),
                ),
                ("languages", models.ManyToManyField(to="django_regional.language")),
                (
                    "language_sitemap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_sitemaps",
                        to="django_sitemap.languagesitemap",
                    ),
                ),
            ],
        ),
    ]
