# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.6 on 2026-07-15 11:06
# Operations reordered and a data migration spliced in so that
# merge_languages_in_sitemap is mapped onto file_split_mode before the old field is dropped.

from django.db import migrations, models


def set_split_mode_from_merge_flag(apps, schema_editor):
    """merge_languages_in_sitemap=True → WHOLE_CHANNEL (0); False → PER_LANGUAGE (1)."""
    LanguageSitemap = apps.get_model("django_sitemap", "LanguageSitemap")
    LanguageSitemap.objects.filter(merge_languages_in_sitemap=False).update(file_split_mode=1)
    LanguageSitemap.objects.filter(merge_languages_in_sitemap=True).update(file_split_mode=0)


def restore_merge_flag_from_split_mode(apps, schema_editor):
    """Reverse: WHOLE_CHANNEL (0) → True; anything else → False."""
    LanguageSitemap = apps.get_model("django_sitemap", "LanguageSitemap")
    LanguageSitemap.objects.filter(file_split_mode=0).update(merge_languages_in_sitemap=True)
    LanguageSitemap.objects.exclude(file_split_mode=0).update(merge_languages_in_sitemap=False)


class Migration(migrations.Migration):
    dependencies = [
        ("django_regional", "0001_squashed_0006_country_default_currency"),
        ("django_sitemap", "0001_squashed_0010_alter_domainsitemap_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainsitemap",
            name="currencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Currencies this domain serves. Empty means all currencies (no currency filtering). When set, products are restricted to those priced in the currency and {{currency_iso3}} placeholders are rendered per currency.",
                to="django_regional.currency",
            ),
        ),
        migrations.AddField(
            model_name="languagesitemap",
            name="file_split_mode",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "One file for the whole channel (languages merged)"),
                    (1, "Separate file per language"),
                    (2, "Separate file per language and currency"),
                ],
                default=0,
                help_text="How sitemap files are split: one file per channel (languages merged), a separate file per language, or a separate file per language and currency. Currency filtering only works in 'per language and currency' mode (currencies taken from DomainSitemap.currencies).",
            ),
        ),
        migrations.RunPython(set_split_mode_from_merge_flag, restore_merge_flag_from_split_mode),
        migrations.RemoveField(
            model_name="languagesitemap",
            name="merge_languages_in_sitemap",
        ),
    ]
