# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.6 on 2026-07-15 11:41
# The removed PER_LANGUAGE_CURRENCY (2) choice is folded into PER_LANGUAGE (1): currency filtering
# is now driven by DomainSitemap.currencies, so those rows keep their per-language split intent.

from django.db import migrations, models


def fold_currency_mode_into_per_language(apps, schema_editor):
    LanguageSitemap = apps.get_model("django_sitemap", "LanguageSitemap")
    LanguageSitemap.objects.filter(file_split_mode=2).update(file_split_mode=1)


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_sitemap",
            "0011_remove_languagesitemap_merge_languages_in_sitemap_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(fold_currency_mode_into_per_language, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="languagesitemap",
            name="file_split_mode",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "One file for the whole channel (languages merged)"),
                    (1, "Separate file per language"),
                ],
                default=0,
                help_text="How sitemap files are split by language: one file per channel (languages merged) or a separate file per language. Currency filtering and splitting is independent — driven by the 'currencies' field on DomainSitemap (currencies set there = filter + separate files).",
            ),
        ),
    ]
