# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.6 on 2026-07-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_regional", "0001_squashed_0006_country_default_currency"),
        ("django_sitemap", "0012_alter_languagesitemap_file_split_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainsitemap",
            name="countries",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Countries this domain serves (main pool). Empty means no country dimension. When set, "
                    "one file set per country + {{country_iso2}} placeholders. A connected "
                    "`sitemap_product_countries` signal receiver can additionally narrow individual SKUs to a "
                    "subset of these countries; a SKU absent from the signal (or with an empty list) is served "
                    "in all of them."
                ),
                to="django_regional.country",
            ),
        ),
    ]
